version: '3'
services:
  xnat-web:
     build:
       context: ./tomcat
       args:
         LOCALE: $LOCALE
     ports:
       - "8081:8080"
       - "8104:8104"
     volumes:
       - $CINDER_DIR/webapps:/opt/tomcat/webapps
       - $CINDER_DIR/plugins:/data/xnat/home/plugins
       - $CINDER_DIR/auth:/data/xnat/home/auth
       - $CINDER_DIR/logs:/data/xnat/home/logs
       - $CINDER_DIR/tomcat-logs:/opt/tomcat/logs
       - $CINDER_DIR/pipeline:/data/xnat/pipeline
       - $CINDER_DIR/build:/data/xnat/build
       - $DATA_DIR/archive:/data/xnat/archive
       - $DATA_DIR/prearchive:/data/xnat/prearchive
       - $DATA_DIR/cache:/data/xnat/cache
       - $DATA_DIR/ftp:/data/xnat/ftp
       - /var/run/docker.sock:/var/run/docker.sock
     expose:
       - "80"
     depends_on:
       - xnat-db
     environment:
       - CATALINA_OPTS=-Xms128m -Xmx1024m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
       - XNAT_HOME=/data/xnat/home
       - TZ=$TIMEZONE
  xnat-db:
     build: ./postgres
     expose:
       - "5432"
     volumes:
       - $CINDER_DIR/postgres:/var/lib/postgresql/data
     environment:
       - TZ=$TIMEZONE
  prometheus:
     image: prom/prometheus
     volumes:
       - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
     command:
       - '--config.file=/etc/prometheus/prometheus.yaml'
     ports:
       - '9090:9090'
     links:
       - cadvisor
     environment:
       - TZ=$TIMEZONE
  cadvisor:
     image: google/cadvisor
     volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
     ports:
       - "8082:8080"
     expose:
       - 8082
     environment:
       - TZ=$TIMEZONE
